In [4]:
import pandas as pd
import numpy as np

datos = pd.read_excel('reporte.xlsx', sheet_name='Hoja1')

datos

,order,openTime,Type,Size,Symbol,openPrice,S/L,T/P,closeTime,closePrice,Commission,Taxes,Swap,Profit
0,232892938,2020.02.06 15:56:26,balance,ADJUSTMENT,5 000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,233104443,2020.02.10 23:24:52,buy,0.01,eurusd-2,1.09117,1.09050,1.09125,2020.02.11 00:42:38,1.09125,0.0,0.0,0.0,0.08
2,233130783,2020.02.11 00:00:59,balance,Financing,-0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,233217598,2020.02.11 23:42:23,buy,0.01,usdcad-2,1.32901,1.32880,0.00000,2020.02.11 23:43:10,1.32879,0.0,0.0,0.0,-0.17
4,233217685,2020.02.11 23:45:15,buy,0.01,usdcad-2,1.32891,1.32750,0.00000,2020.02.12 09:41:11,1.32750,0.0,0.0,0.0,-1.06
5,233247211,2020.02.12 00:01:04,balance,Financing,-0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,233489119,2020.02.14 20:42:36,buy,0.1,eurusd-2,1.08448,1.08117,0.00000,2020.02.18 15:19:24,1.08117,0.0,0.0,0.0,-33.10
7,233523289,2020.02.15 00:01:21,balance,Financing,-1.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,233599745,2020.02.18 00:00:53,balance,Financing,-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,233691065,2020.02.19 00:01:08,balance,Financing,-1.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,233776350,2020.02.20 00:01:05,balance,Financing,-2.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,233865072,2020.02.21 00:00:58,balance,Financing,-3.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,233948416,2020.02.22 00:00:51,balance,Financing,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
def f_leer_archivo(param_archivo):
     # Leer archivo de datos y guardarlo en un DataFrame
    df_data = pd.read_excel( 'reporte.xlsx', sheet_name='Hoja1')
    df_data = df_data.loc[df_data['Type']!='balance']
    
    # elegir solo renglones en los que la columna type == buy | type == sell
    df_data = df_data[(df_data['Type'] == 'buy') | (df_data['Type'] == 'sell') |
                        (df_data['Type'] == 's/l')
                        | (df_data['Type'] == 't/p')]
    
    # Convertir en minusculas el nombre de las columnas
    df_data.columns = [list(df_data.columns)[i].lower()
                       for i in range(0, len(df_data.columns))]
    

    #print(df_data)
    return df_data

In [6]:
df_archivo = f_leer_archivo(param_archivo="reporte.xlsx")
df_archivo = df_archivo.reset_index()
df_archivo.head()

,index,order,opentime,type,size,symbol,openprice,s/l,t/p,closetime,closeprice,commission,taxes,swap,profit
0,1,233104443,2020.02.10 23:24:52,buy,0.01,eurusd-2,1.09117,1.09050,1.09125,2020.02.11 00:42:38,1.09125,0.0,0.0,0.0,0.08
1,3,233217598,2020.02.11 23:42:23,buy,0.01,usdcad-2,1.32901,1.32880,0.00000,2020.02.11 23:43:10,1.32879,0.0,0.0,0.0,-0.17
2,4,233217685,2020.02.11 23:45:15,buy,0.01,usdcad-2,1.32891,1.32750,0.00000,2020.02.12 09:41:11,1.32750,0.0,0.0,0.0,-1.06
3,6,233489119,2020.02.14 20:42:36,buy,0.1,eurusd-2,1.08448,1.08117,0.00000,2020.02.18 15:19:24,1.08117,0.0,0.0,0.0,-33.10

In [7]:
# -- ------------------------------------------------------ FUNCION: Pips por instrumento -- #
# -- ------------------------------------------------------------------------------------ -- #
# -- calcular el tamaño de los pips por instrumento

def f_pip_size(param_ins):
    """
           Parameters
       ----------
       param_ins : str : nombre de instrumento
       Returns
       -------
       Debugging
       -------
       param_ins = 'usdjpy'
       """

    # encontrar y eliminar un guion bajo
    # inst = param_ins.replace('_', '')

    # transformar a minusculas
    inst = param_ins.lower()

    # lista de pips por instrumento
    pips_inst = {'usdjpy': 100, 'gbpjpy': 100, 'eurjpy': 100, 'cadjpy': 100,
                 'chfjpy': 100,
                 'eurusd': 10000, 'gbpusd': 10000, 'usdcad': 10000, 'usdmxn': 10000,
                 'audusd': 10000, 'nzdusd': 10000,
                 'usdchf': 10000,
                 'eurgbp': 10000, 'eurchf': 10000, 'eurnzd': 10000, 'euraud': 10000,
                 'gbpnzd': 10000, 'gbpchf': 10000, 'gbpaud': 10000,
                 'audnzd': 10000, 'nzdcad': 10000, 'audcad': 10000,
                 'xauusd': 10, 'xagusd': 10, 'btcusd': 10, 'wticousd':10,'natgasusd':10}

    return pips_inst[inst]

In [8]:
f_pip_size(param_ins = 'usdcad')

10000

In [9]:
#columna de tiempos
df_tiempos = df_archivo[['opentime','closetime']]
df_tiempos.head()

              opentime            closetime
0  2020.02.10 23:24:52  2020.02.11 00:42:38
1  2020.02.11 23:42:23  2020.02.11 23:43:10
2  2020.02.11 23:45:15  2020.02.12 09:41:11
3  2020.02.14 20:42:36  2020.02.18 15:19:24

In [10]:
from datetime import  datetime
from datetime import timedelta

def dif_tiempos(data):

    df = pd.DataFrame(data=df_tiempos)
    df['opentime'] = pd.to_datetime(df_tiempos['opentime'])
    df['closetime'] = pd.to_datetime(df_tiempos['closetime'])

    Time = df['closetime'] - df['opentime']
    Time = Time.dt.seconds
    Time = pd.DataFrame(Time)
    df_archivo['Time'] = Time
    return df_archivo

In [11]:
dif_tiempos(df_tiempos)

#quitar el 2 de los items
df_archivo['symbol'] = df_archivo['symbol'].replace('eurusd-2','eurusd').replace('usdcad-2','usdcad').replace('usdcad-2','usdcad').replace('eurusd-2','eurusd')
df_archivo.head()

,index,order,opentime,type,size,symbol,openprice,s/l,t/p,closetime,closeprice,commission,taxes,swap,profit,Time
0,1,233104443,2020.02.10 23:24:52,buy,0.01,eurusd,1.09117,1.09050,1.09125,2020.02.11 00:42:38,1.09125,0.0,0.0,0.0,0.08,4666
1,3,233217598,2020.02.11 23:42:23,buy,0.01,usdcad,1.32901,1.32880,0.00000,2020.02.11 23:43:10,1.32879,0.0,0.0,0.0,-0.17,47
2,4,233217685,2020.02.11 23:45:15,buy,0.01,usdcad,1.32891,1.32750,0.00000,2020.02.12 09:41:11,1.32750,0.0,0.0,0.0,-1.06,35756
3,6,233489119,2020.02.14 20:42:36,buy,0.1,eurusd,1.08448,1.08117,0.00000,2020.02.18 15:19:24,1.08117,0.0,0.0,0.0,-33.10,67008

In [12]:
# -- ------------------------------------------------------------------------------------ -- #
# -- calcular el tamaño de los pips por instrumento

def f_pip_size(param_ins):
    """
           Parameters
       ----------
       param_ins : str : nombre de instrumento
       Returns
       -------
       Debugging
       -------
       param_ins = 'usdjpy'
       """

    # encontrar y eliminar un guion bajo
    # inst = param_ins.replace('_', '')

    # transformar a minusculas
    inst = param_ins.lower()

    # lista de pips por instrumento
    pips_inst = {'usdjpy': 100, 'gbpjpy': 100, 'eurjpy': 100, 'cadjpy': 100,
                 'chfjpy': 100,
                 'eurusd': 10000, 'gbpusd': 10000, 'usdcad': 10000, 'usdmxn': 10000,
                 'audusd': 10000, 'nzdusd': 10000,
                 'usdchf': 10000,
                 'eurgbp': 10000, 'eurchf': 10000, 'eurnzd': 10000, 'euraud': 10000,
                 'gbpnzd': 10000, 'gbpchf': 10000, 'gbpaud': 10000,
                 'audnzd': 10000, 'nzdcad': 10000, 'audcad': 10000,
                 'xauusd': 10, 'xagusd': 10, 'btcusd': 10, 'wticousd':10,'natgasusd':10}

    return pips_inst[inst]

In [14]:
# obtenemos los pips de todos los inttrumentos uilizados y anexamos al dataframe
pips = [f_pip_size(param_ins = df_archivo['symbol'][i]) for i in range(len(df_archivo))]
df_archivo['pips'] =pips

In [15]:
#calculamos las diferencias entre entrada y salida de la operacion y multiplicamos por su valor equivalente
#deltasprice = [n for n in range(len(newd)) if n%2 == 0]
piptotales = []
conta = 0
for i in range(0,len(df_archivo)):
    if df_archivo['symbol'][i] == 'buy':
        piptotales.append((df_archivo['closeprice'][i] - df_archivo['openprice'][i])*pips[i])
    else:
        piptotales.append((df_archivo['openprice'][i] - df_archivo['closeprice'][i])*pips[i])
    conta = conta + 1
df_archivo['piptotales'] = piptotales
df_archivo['profit_t'] = df_archivo['profit'].cumsum() 
df_archivo

,index,order,opentime,type,size,symbol,openprice,s/l,t/p,closetime,closeprice,commission,taxes,swap,profit,Time,pips,piptotales,profit_t
0,1,233104443,2020.02.10 23:24:52,buy,0.01,eurusd,1.09117,1.09050,1.09125,2020.02.11 00:42:38,1.09125,0.0,0.0,0.0,0.08,4666,10000,-0.8,0.08
1,3,233217598,2020.02.11 23:42:23,buy,0.01,usdcad,1.32901,1.32880,0.00000,2020.02.11 23:43:10,1.32879,0.0,0.0,0.0,-0.17,47,10000,2.2,-0.09
2,4,233217685,2020.02.11 23:45:15,buy,0.01,usdcad,1.32891,1.32750,0.00000,2020.02.12 09:41:11,1.32750,0.0,0.0,0.0,-1.06,35756,10000,14.1,-1.15
3,6,233489119,2020.02.14 20:42:36,buy,0.1,eurusd,1.08448,1.08117,0.00000,2020.02.18 15:19:24,1.08117,0.0,0.0,0.0,-33.10,67008,10000,33.1,-34.25

In [16]:
def f_estadisticas_ba(newd):
    return pd.DataFrame({
        'Ops totales': [len(df_archivo['order']), 'Operaciones totales'],
        'Ganadoras': [len(df_archivo[df_archivo['piptotales']>=0]), 'Operaciones ganadoras'],
        'Ganadoras_c': [len(df_archivo[(df_archivo['type']=='buy') & (df_archivo['piptotales']>=0)]), 'Operaciones ganadoras de compra'],
        'Ganadoras_s': [len(df_archivo[(df_archivo['type']=='sell') & (df_archivo['piptotales']>=0)]), 'Operaciones ganadoras de venta'],
        'Perdedoras': [len(df_archivo[df_archivo['piptotales'] < 0]), 'Operaciones perdedoras'],
        'Perdedoras_c': [len(df_archivo[(df_archivo['type']=='buy') & (df_archivo['piptotales']<0)]), 'Operaciones perdedoras de compra'],
        'Perdedoras_s': [len(df_archivo[(df_archivo['type']=='sell') & (df_archivo['piptotales']<0)]), 'Operaciones perdedoras de venta'],
        'Mediana_profit': [df_archivo['profit'].median(), 'Mediana de profit de operaciones'],
        'Mediana_pips': [df_archivo['piptotales'].median(), 'Mediana de pips de las operaciones'],
        'r_efectividad': [len(df_archivo[df_archivo['piptotales']>=0])/len(df_archivo),
                'Ganadoras Totales/Operaciones Totales'],
      #  'r_proporcion': [if (len(newd[newd['piptotales'] < 0]) < 0:
       #                        [len(newd[newd['piptotales']>=0])/len(newd[newd['piptotales'] < 0])
        #                else: 
         #                       0],'Perdedoras Totales/Ganadoras Totales'],
        #'r_efectividad_c': [len(newd[(newd['type']=='buy') & (newd['piptotales']>=0)])/len(newd),
         #                   'Ganadoras Compras/Operaciones Totales'],
        #'r_efectividad_v': [len(newd[(newd['type']=='sell') & (newd['piptotales']>=0)])/len(newd),
         #                  'Ganadoras Ventas/ Operaciones Totales']
    })

In [19]:
estadisticas_ba = f_estadisticas_ba(df_archivo).T
estadisticas_ba.index.name = 'medida'
estadisticas_ba.columns = ['valor', 'descripcion']  
estadisticas_ba

                valor                            descripcion
medida
Ops totales         4                    Operaciones totales
Ganadoras           3                  Operaciones ganadoras
Ganadoras_c         3        Operaciones ganadoras de compra
Ganadoras_s         0         Operaciones ganadoras de venta
Perdedoras          1                 Operaciones perdedoras
Perdedoras_c        1       Operaciones perdedoras de compra
Perdedoras_s        0        Operaciones perdedoras de venta
Mediana_profit -0.615       Mediana de profit de operaciones
Mediana_pips     8.15     Mediana de pips de las operaciones
r_efectividad    0.75  Ganadoras Totales/Operaciones Totales

In [20]:
def f_estadisticas_ranking(df_archivo):
    return pd.DataFrame({
        'Ops totales': [len(df_archivo['order']), 'Operaciones totales'],
        'Ganadoras': [len(df_archivo[df_archivo['piptotales']>=0]), 'Operaciones ganadoras'],
        'Ganadoras_c': [len(df_archivo[(df_archivo['type']=='buy') & (df_archivo['piptotales']>=0)]), 'Operaciones ganadoras de compra'],
        'Ganadoras_s': [len(df_archivo[(df_archivo['type']=='sell') & (df_archivo['piptotales']>=0)]), 'Operaciones ganadoras de venta'],
        'Perdedoras': [len(df_archivo[df_archivo['piptotales'] < 0]), 'Operaciones perdedoras'],
        'Perdedoras_c': [len(df_archivo[(df_archivo['type']=='buy') & (df_archivo['piptotales']<0)]), 'Operaciones perdedoras de compra'],
        'Perdedoras_s': [len(df_archivo[(df_archivo['type']=='sell') & (df_archivo['piptotales']<0)]), 'Operaciones perdedoras de venta'],
        'Mediana_profit': [df_archivo['profit'].median(), 'Mediana de profit de operaciones'],
        'Mediana_pips': [df_archivo['piptotales'].median(), 'Mediana de pips de las operaciones'],
        'r_efectividad': [len(df_archivo[df_archivo['piptotales']>=0])/len(df_archivo),
                'Ganadoras Totales/Operaciones Totales'],
      #  'r_proporcion': [if (len(newd[newd['piptotales'] < 0]) < 0:
       #                        [len(newd[newd['piptotales']>=0])/len(newd[newd['piptotales'] < 0])
        #                else: 
         #                       0],'Perdedoras Totales/Ganadoras Totales'],
        #'r_efectividad_c': [len(newd[(newd['type']=='buy') & (newd['piptotales']>=0)])/len(newd),
         #                   'Ganadoras Compras/Operaciones Totales'],
        #'r_efectividad_v': [len(newd[(newd['type']=='sell') & (newd['piptotales']>=0)])/len(newd),
         #                  'Ganadoras Ventas/ Operaciones Totales']
    })

In [21]:
import collections
counter=collections.Counter(df_archivo['symbol'])
ranking = pd.DataFrame(counter, index=[0]).T
ranking

        0
eurusd  2
usdcad  2